# Form implementation generated from reading ui file 'AusgabeDialogUI.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(621, 174)
        font = QtGui.QFont()
        font.setPointSize(11)
        Dialog.setFont(font)
        icon = QtGui.QIcon.fromTheme("dialog-question")
        Dialog.setWindowIcon(icon)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 120, 571, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.StandardButton.Cancel
            | QtWidgets.QDialogButtonBox.StandardButton.Ok
        )
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 30, 581, 61))
        self.groupBox.setObjectName("groupBox")
        self.le_rename = QtWidgets.QLineEdit(parent=self.groupBox)
        self.le_rename.setGeometry(QtCore.QRect(10, 20, 561, 31))
        self.le_rename.setObjectName("le_rename")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)  # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject)  # type: ignore

        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(
            _translate("Dialog", "Name der Ausgabe bearbeiten/bestätigen")
        )
        self.groupBox.setTitle(_translate("Dialog", "Name der AusgabeDatei"))

    def setAusgabeName(self, name):
        self.le_rename.setText(name)

    def getAusgabeName(self):
        return self.le_rename.text()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
