# Form implementation generated from reading ui file 'frm_pdfdec.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_frm_pdfDec(object):
    def setupUi(self, frm_pdfDec):
        frm_pdfDec.setObjectName("frm_pdfDec")
        frm_pdfDec.setEnabled(True)
        frm_pdfDec.resize(841, 887)
        frm_pdfDec.setStyleSheet("background-color: rgb(113, 139, 139)")
        self.lbl_img = QtWidgets.QLabel(parent=frm_pdfDec)
        self.lbl_img.setGeometry(QtCore.QRect(0, 0, 671, 841))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_img.setFont(font)
        self.lbl_img.setAutoFillBackground(False)
        self.lbl_img.setStyleSheet("background-color: rgb(255, 244, 189)")
        self.lbl_img.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_img.setObjectName("lbl_img")
        self.lbl_datei = QtWidgets.QLabel(parent=frm_pdfDec)
        self.lbl_datei.setGeometry(QtCore.QRect(0, 850, 671, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_datei.setFont(font)
        self.lbl_datei.setAutoFillBackground(False)
        self.lbl_datei.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.lbl_datei.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.lbl_datei.setObjectName("lbl_datei")
        self.btn_finden = QtWidgets.QPushButton(parent=frm_pdfDec)
        self.btn_finden.setGeometry(QtCore.QRect(690, 10, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_finden.setFont(font)
        self.btn_finden.setStyleSheet("background-color: rgb(190, 202, 109)")
        self.btn_finden.setObjectName("btn_finden")
        self.btn_ende = QtWidgets.QPushButton(parent=frm_pdfDec)
        self.btn_ende.setGeometry(QtCore.QRect(690, 830, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.btn_ende.setFont(font)
        self.btn_ende.setStyleSheet("background-color: rgb(190, 202, 109)")
        self.btn_ende.setObjectName("btn_ende")
        self.lbl_decrypted = QtWidgets.QLabel(parent=frm_pdfDec)
        self.lbl_decrypted.setEnabled(True)
        self.lbl_decrypted.setGeometry(QtCore.QRect(690, 410, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.lbl_decrypted.setFont(font)
        self.lbl_decrypted.setStyleSheet("color: rgb(200, 0, 0)")
        self.lbl_decrypted.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.lbl_decrypted.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.lbl_decrypted.setLineWidth(3)
        self.lbl_decrypted.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_decrypted.setObjectName("lbl_decrypted")

        self.retranslateUi(frm_pdfDec)
        QtCore.QMetaObject.connectSlotsByName(frm_pdfDec)

    def retranslateUi(self, frm_pdfDec):
        _translate = QtCore.QCoreApplication.translate
        frm_pdfDec.setWindowTitle(_translate("frm_pdfDec", "pdf entschlüsseln"))
        self.lbl_img.setText(_translate("frm_pdfDec", "Datei hierhin ziehen"))
        self.lbl_datei.setText(_translate("frm_pdfDec", "TextLabel"))
        self.btn_finden.setText(_translate("frm_pdfDec", "pdf suchen"))
        self.btn_ende.setText(_translate("frm_pdfDec", "Ende"))
        self.lbl_decrypted.setText(_translate("frm_pdfDec", "entschlüsselt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    frm_pdfDec = QtWidgets.QWidget()
    ui = Ui_frm_pdfDec()
    ui.setupUi(frm_pdfDec)
    frm_pdfDec.show()
    sys.exit(app.exec())
